cmake_minimum_required(VERSION 3.8)
project(scara_description)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)

install(
  DIRECTORY urdf meshes launch config
  DESTINATION share/${PROJECT_NAME}
)

install(
  PROGRAMS
    scripts/scara_teleop.py
    scripts/pick_and_place.py
    scripts/launch_mujoco.py
    scripts/scara_mujoco_teleop.py
  DESTINATION lib/${PROJECT_NAME}
)

ament_package()
